{% set name = "pytim" %}
{% set version = "0.8.1" %}
{% set sha256 = "93e934beaead8161404579311d547f7d0320ed21d3f54433f75e69b140c2f7c9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  skip: True  # [py3k or win]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython >=0.24.1
    - scipy >=1.0
    - numpy
  run:
    - python
    - scipy >=1.0
    - {{ pin_compatible('numpy') }}
    - scikit-image >=0.13.0
    - mdanalysis >=0.17
    - pywavelets >=0.5.2

test:
  imports:
    - MDAnalysis
    - pytim
    - pytim.datafiles

about:
  home: http://github.com/Marcello-Sega/pytim
  license: GPL-3.0
  license_family: GPL
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'A python based tool for interfacial molecules analysis'
  description: |
    Pytim provides a set of tools for interfacial analysis in molecular simulations.
    Most major configuration and trajectory formats can be read, thanks to MDAnalysis.
  doc_url: https://marcello-sega.github.io/pytim/
  dev_url: https://github.com/Marcello-Sega/pytim

extra:
  recipe-maintainers:
    - Marcello-Sega
