{% set name = "pytim" %}
{% set version = "0.8.4" %}
{% set sha256 = "bc76da641b4aa1b1264a8b84b331a1db99bb84a705be415d12281e123235b180" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [py2k or win or osx]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython >=0.24.1
    - scipy >=1.1.0
    - numpy >=1.16.0
  run:
    - python
    - scipy >=1.1.0
    - {{ pin_compatible('numpy') }}
    - scikit-image >=0.14.2
    - mdanalysis >=0.19
    - pywavelets >=0.5.2

test:
  imports:
    - MDAnalysis
    - pytim
    - pytim.datafiles

about:
  home: http://github.com/Marcello-Sega/pytim
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: A python based tool for interfacial molecules analysis
  description: |
    Pytim provides a set of tools for interfacial analysis in molecular simulations.
    Most major configuration and trajectory formats can be read, thanks to MDAnalysis.
  doc_url: https://marcello-sega.github.io/pytim/
  dev_url: https://github.com/Marcello-Sega/pytim

extra:
  recipe-maintainers:
    - Marcello-Sega
