{% set name = "pytim" %}
{% set version = "0.8.0" %}
{% set sha256 = "d5a65559becebb30fb1ae7b3b769a10cffa484539c2fb246f8f25271b66dc7eb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [py3k or win]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python 
    - setuptools
    - cython >=0.24.1
    - scipy >=1.0
    - toolchain
    - numpy >=1.14.0
  run:
    - python >=2.7
    - scipy >=1.0
    - numpy >=1.14.0
    - scikit-image >=0.13.0
    - mdanalysis >=0.17
    - pywavelets >=0.5.2

test:
  imports:
    - MDAnalysis
    - pytim
    - pytim.datafiles

about:
  home: http://github.com/Marcello-Sega/pytim
  license: GPL-3.0
  license_family: GPL
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'A python based tool for interfacial molecules analysis'
  description: |
    Pytim provides a set of tools for interfacial analysis in molecular simulations.
    Most major configuration and trajectory formats can be read, thanks to MDAnalysis.
  doc_url: https://marcello-sega.github.io/pytim/
  dev_url: https://github.com/Marcello-Sega/pytim

extra:
  recipe-maintainers:
    - Marcello-Sega
