{% set name = "pytim" %}
{% set version = "1.0.4" %}
{% set sha256 = "5bcda199b1fdb34abf1f3b71e5cec43663d5fdd472dce1ed69ce34e3fa646a67" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py2k or win or python_impl == 'pypy' or py<310]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - cython >=0.24.1
    - scipy >=1.1.0
    - numpy >=1.26.4,<2.0.0
  run:
    - python
    - scipy >=1.6.0
    - scikit-image >=0.14.2
    - gsd >3.0.0
    - {{ pin_compatible('numpy') }}
    - scikit-image >=0.14.2
    - mdanalysis >=2.7.0
    - pywavelets >=0.5.2

test:
  imports:
    - MDAnalysis
    - pytim
    - pytim.datafiles

about:
  home: http://github.com/Marcello-Sega/pytim
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: A python based tool for interfacial molecules analysis
  description: |
    Pytim provides a set of tools for interfacial analysis in molecular simulations.
    Most major configuration and trajectory formats can be read, thanks to MDAnalysis.
  doc_url: https://marcello-sega.github.io/pytim/
  dev_url: https://github.com/Marcello-Sega/pytim

extra:
  recipe-maintainers:
    - Marcello-Sega
